name: BeRich

options:
  minimumXcodeGenVersion: 2.17
  deploymentTarget: 
    iOS: "16.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  defaultConfig: Debug
  developmentLanguage: ru

fileGroups:
  - BeRich

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.5
    ENABLE_TESTABILITY: YES
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UILaunchStoryboardName: SplashScreen.storyboard
    INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
    INFOPLIST_KEY_UIViewControllerBasedStatusBarAppearance: NO
  configs:
    Debug:
      ENABLE_TESTABILITY: YES
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      VALIDATE_PRODUCT: NO
    Release:
      ENABLE_TESTABILITY: NO
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      VALIDATE_PRODUCT: YES

targets:

  BeRich:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: BeRich
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1"
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        PRODUCT_BUNDLE_IDENTIFIER: "BeRich-Team.BeRich"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_ASSET_PATHS: "\"BeRich/Preview Content\""
        ENABLE_PREVIEWS: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1.0.0
        CODE_SIGN_IDENTITY: iPhone Developer
        DEFINES_MODULE: YES
        XCODEGEN_STATE: YES
        PRODUCT_NAME: "$(TARGET_NAME)"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        LD_RUNPATH_SEARCH_PATHS:
        - "$(inherited)"
        - "@executable_path/Frameworks"
    preBuildScripts:
    - script: |
        if which swiftformat >/dev/null; then
          swiftformat --lint --swiftversion 5.5 $SRCROOT
        else
          echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
        fi
        exit 0
      name: Lint
      basedOnDependencyAnalysis: NO

  BeRichTests:
    type: bundle.unit-test
    platform: iOS
    scheme:
      testTargets:
      - BeRichTests
    sources:
      - path: BeRichTests
    dependencies:
      - target: BeRich
